package cn.llyong.module.domain.user;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table cm_user
 *
 * @mbg.generated do_not_delete_during_merge Tue Aug 07 10:33:19 CST 2018
 */
public class CmUser implements Serializable {
    /**
     * Database Column Remarks:
     *   用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_user.USER_ID
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   用户名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_user.USERNAME
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    private String username;

    /**
     * Database Column Remarks:
     *   密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_user.PASSWORD
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    private String password;

    /**
     * Database Column Remarks:
     *   部门ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_user.DEPT_ID
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    private Long deptId;

    /**
     * Database Column Remarks:
     *   邮箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_user.EMAIL
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    private String email;

    /**
     * Database Column Remarks:
     *   联系电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_user.MOBILE
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    private String mobile;

    /**
     * Database Column Remarks:
     *   状态 0锁定 1有效
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_user.STATUS
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    private String status;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_user.CRATE_TIME
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    private Date crateTime;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_user.MODIFY_TIME
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    private Date modifyTime;

    /**
     * Database Column Remarks:
     *   最近访问时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_user.LAST_LOGIN_TIME
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    private Date lastLoginTime;

    /**
     * Database Column Remarks:
     *   性别 0男 1女
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_user.SSEX
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    private String ssex;

    /**
     * Database Column Remarks:
     *   主题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_user.THEME
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    private String theme;

    /**
     * Database Column Remarks:
     *   头像
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_user.AVATAR
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    private String avatar;

    /**
     * Database Column Remarks:
     *   描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_user.DESCRIPTION
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cm_user
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_user.USER_ID
     *
     * @return the value of cm_user.USER_ID
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_user.USER_ID
     *
     * @param userId the value for cm_user.USER_ID
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_user.USERNAME
     *
     * @return the value of cm_user.USERNAME
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_user.USERNAME
     *
     * @param username the value for cm_user.USERNAME
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_user.PASSWORD
     *
     * @return the value of cm_user.PASSWORD
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_user.PASSWORD
     *
     * @param password the value for cm_user.PASSWORD
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_user.DEPT_ID
     *
     * @return the value of cm_user.DEPT_ID
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    public Long getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_user.DEPT_ID
     *
     * @param deptId the value for cm_user.DEPT_ID
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    public void setDeptId(Long deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_user.EMAIL
     *
     * @return the value of cm_user.EMAIL
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_user.EMAIL
     *
     * @param email the value for cm_user.EMAIL
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_user.MOBILE
     *
     * @return the value of cm_user.MOBILE
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_user.MOBILE
     *
     * @param mobile the value for cm_user.MOBILE
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_user.STATUS
     *
     * @return the value of cm_user.STATUS
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_user.STATUS
     *
     * @param status the value for cm_user.STATUS
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_user.CRATE_TIME
     *
     * @return the value of cm_user.CRATE_TIME
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    public Date getCrateTime() {
        return crateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_user.CRATE_TIME
     *
     * @param crateTime the value for cm_user.CRATE_TIME
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    public void setCrateTime(Date crateTime) {
        this.crateTime = crateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_user.MODIFY_TIME
     *
     * @return the value of cm_user.MODIFY_TIME
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_user.MODIFY_TIME
     *
     * @param modifyTime the value for cm_user.MODIFY_TIME
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_user.LAST_LOGIN_TIME
     *
     * @return the value of cm_user.LAST_LOGIN_TIME
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_user.LAST_LOGIN_TIME
     *
     * @param lastLoginTime the value for cm_user.LAST_LOGIN_TIME
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_user.SSEX
     *
     * @return the value of cm_user.SSEX
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    public String getSsex() {
        return ssex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_user.SSEX
     *
     * @param ssex the value for cm_user.SSEX
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    public void setSsex(String ssex) {
        this.ssex = ssex == null ? null : ssex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_user.THEME
     *
     * @return the value of cm_user.THEME
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    public String getTheme() {
        return theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_user.THEME
     *
     * @param theme the value for cm_user.THEME
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    public void setTheme(String theme) {
        this.theme = theme == null ? null : theme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_user.AVATAR
     *
     * @return the value of cm_user.AVATAR
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_user.AVATAR
     *
     * @param avatar the value for cm_user.AVATAR
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_user.DESCRIPTION
     *
     * @return the value of cm_user.DESCRIPTION
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_user.DESCRIPTION
     *
     * @param description the value for cm_user.DESCRIPTION
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_user
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", deptId=").append(deptId);
        sb.append(", email=").append(email);
        sb.append(", mobile=").append(mobile);
        sb.append(", status=").append(status);
        sb.append(", crateTime=").append(crateTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", lastLoginTime=").append(lastLoginTime);
        sb.append(", ssex=").append(ssex);
        sb.append(", theme=").append(theme);
        sb.append(", avatar=").append(avatar);
        sb.append(", description=").append(description);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}