package cn.llyong.module.domain.user;

import cn.llyong.module.domain.user.CmUser;
import cn.llyong.module.domain.user.CmUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CmUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_user
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    long countByExample(CmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_user
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    int deleteByExample(CmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_user
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_user
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    int insert(CmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_user
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    int insertSelective(CmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_user
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    List<CmUser> selectByExampleWithRowbounds(CmUserExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_user
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    List<CmUser> selectByExample(CmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_user
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    CmUser selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_user
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    int updateByExampleSelective(@Param("record") CmUser record, @Param("example") CmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_user
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    int updateByExample(@Param("record") CmUser record, @Param("example") CmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_user
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    int updateByPrimaryKeySelective(CmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_user
     *
     * @mbg.generated Tue Aug 07 10:33:19 CST 2018
     */
    int updateByPrimaryKey(CmUser record);
}